default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: admin
  password: admin
  host: db
  port: 3306

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  username: your_production_username
  password: your_production_password
