default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgregui
  password: uKTSmWKKf7lPrYAUrLvJ2Hi1SzqYEdl4
  host: dpg-cqv01cd6l47c7383apu0-a

development:
  <<: *default
  database: postgregui

test:
  <<: *default
  database: postgregui

production:
  <<: *default
  database: postgregui
  username: postgregui
  password: uKTSmWKKf7lPrYAUrLvJ2Hi1SzqYEdl4
