source 'https://rubygems.org'

gem 'rails', '~> 7.0.8'
gem 'pg', '~> 1.5', '>= 1.5.7'
gem 'puma', '~> 5.6'
gem 'bootsnap', '~> 1.18', '>= 1.18.4'
gem 'rack-cors', require: 'rack/cors'
gem 'nokogiri', '~> 1.16', '>= 1.16.7'
gem 'httparty', '~> 0.22.0'
gem 'bitly', '~> 3.0'

group :test, :development do
  gem 'rspec', '~> 3.13'
  gem 'rspec-rails', '~> 6.1', '>= 6.1.3'
  gem 'rspec-mocks', '~> 3.13', '>= 3.13.1'
  gem 'byebug', '~> 11.1', '>= 11.1.3'
  gem 'faker', '~> 3.4', '>= 3.4.2'
  gem 'factory_bot_rails', '~> 6.4', '>= 6.4.3'
  gem 'simplecov', '~> 0.22.0'
  gem 'webmock', '~> 3.23', '>= 3.23.1'
end